# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist/'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://ftp.suit.pe'
    username: 'devftp'
    password: 'FTPuser2019'
    rootDirectory: '$(System.DefaultWorkingDirectory)/dist/'
    filePatterns: '**'
    remoteDirectory: '/logistica.dgallia.suit.pe/'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: false