trigger:
- feature/*

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'dev-frontend-server'
    rootDirectory: '$(System.DefaultWorkingDirectory)/dist/'
    filePatterns: '**'
    remoteDirectory: '/dgallia.suit.pe/'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: false